services:

  minio:
    image: minio/minio
    container_name: diep-minio

    restart: unless-stopped

    ports:
      - "9000:9000"
      - "9002:9001"

    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}

    volumes:
      - minio-data:/data

    command: server /data --console-address ":9001"

volumes:
  minio-data:

networks:
  default:
    name: diep-net
    external: true
