"""Read-only Operator API foundation for WP-013-02."""

from .api import OperatorApi
from .auth import (
    OPERATOR_ROLE,
    READ_ROLES,
    VIEWER_ROLE,
    StaticTokenAuthenticator,
    require_read_access,
)
from .http import API_PREFIX, create_operator_api_app
from .models import (
    API_VERSION,
    AssetSearchResult,
    AssetStatePanel,
    AuditRecordView,
    AuthenticationError,
    AuthorizationError,
    DashboardView,
    EdgeView,
    ExplanationView,
    FaultCandidateView,
    FeederStatusView,
    HistoryWorkspaceView,
    NetworkWorkspaceView,
    NodeView,
    OperationalIndicator,
    OperatorApiError,
    OperatorPrincipal,
    OutageOverview,
    PlatformStatus,
    RecommendationStepView,
    RecommendationWorkspaceView,
    RuleOutcomeView,
    ServiceHealth,
    StrategyView,
    TimelineEntryView,
    TopologyNeighborhood,
    UnknownAssetError,
)
from .service import OperatorViewService

__all__ = [
    "API_PREFIX",
    "API_VERSION",
    "OPERATOR_ROLE",
    "READ_ROLES",
    "VIEWER_ROLE",
    "AssetSearchResult",
    "AssetStatePanel",
    "AuditRecordView",
    "AuthenticationError",
    "AuthorizationError",
    "DashboardView",
    "EdgeView",
    "ExplanationView",
    "FaultCandidateView",
    "FeederStatusView",
    "HistoryWorkspaceView",
    "NetworkWorkspaceView",
    "NodeView",
    "OperationalIndicator",
    "OperatorApi",
    "OperatorApiError",
    "OperatorPrincipal",
    "OperatorViewService",
    "OutageOverview",
    "PlatformStatus",
    "RecommendationStepView",
    "RecommendationWorkspaceView",
    "RuleOutcomeView",
    "ServiceHealth",
    "StaticTokenAuthenticator",
    "StrategyView",
    "TimelineEntryView",
    "TopologyNeighborhood",
    "UnknownAssetError",
    "create_operator_api_app",
    "require_read_access",
]
